const CASES = [
  {id:'plombieres-bricks',title:'Plombières tailings in facing bricks',location:'Plombières, Belgium',region:'Europe',material:'Tailings',commodity:'Zinc–lead',waste:'Sulphidic tailings',pathway:'Construction',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:50.736,lng:5.961,summary:'Untreated historic tailings were incorporated into facing-brick blends and assessed for product quality, environmental performance and lifecycle impacts.',technical:'Mineralogical and chemical characterisation, blend trials, fired-product testing and cradle-to-gate lifecycle assessment. The assessed formulations achieved satisfactory properties.',environmental:'The study evaluated regulatory compliance and reported improved lifecycle performance at the higher tailings blend examined. Feed variability and exposure-specific leaching remain necessary checks.',detail:'A well-documented construction-material case showing that sulphidic tailings can form part of a fired product when blend chemistry and environmental behaviour are controlled. It demonstrates laboratory feasibility, not unrestricted product approval.',sourceState:"The study reports that untreated Plombières tailings produced compliant facing-brick blends, with the 40 wt% blend outperforming standard bricks in its lifecycle assessment.",sources:[{label:'Journal of Cleaner Production (2022)',url:'https://www.sciencedirect.com/science/article/pii/S095965262202707X'}],lastReviewed:'23 September 2026'},
  {id:'nador-fired-bricks',title:'Nador iron tailings in fired clay bricks',location:'Nador, Morocco',region:'Africa',material:'Tailings',commodity:'Iron ore',waste:'Iron-ore tailings',pathway:'Construction',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:35.168,lng:-2.934,summary:'Iron-mine tailings from an inactive operation were evaluated as an additive in red-clay fired bricks.',technical:'The study characterised a 60% tailings and 40% red-clay blend and fired specimens at 500°C, 850°C and 1100°C. Tailings specimens reached only 1.25 MPa compressive strength and remained more porous than the reference.',environmental:'Firing can immobilise some constituents but introduces thermal energy and emissions; leaching and kiln-specific performance require verification.',detail:'The study demonstrates that the blend can be formed and fired, but the reported strength and porosity do not establish a specification-ready brick. Further formulation work is required.',sourceState:"Specimens containing 60% tailings reached 1.25 MPa compressive strength and had greater porosity than the reference bricks.",sources:[{label:'University of Liège research record',url:'https://orbi.uliege.be/handle/2268/335849'}],lastReviewed:'23 September 2026'},
  {id:'pamaka-bricks',title:'Pamaka cement–tailings masonry bricks',location:'Pamaka, Suriname',region:'South America',material:'Tailings',commodity:'Gold',waste:'Artisanal gold tailings',pathway:'Construction',stage:'Laboratory',readiness:'Conditional',evidence:'Peer-reviewed study',lat:4.4,lng:-54.4,summary:'Artisanal gold-mining waste was tested in cement-bound bricks intended for non-loadbearing masonry.',technical:'Mix-ratio trials included compressive strength, water absorption and assessment of gold and mercury. Reported strengths met the cited non-loadbearing criteria.',environmental:'Mercury-bearing residues demand conservative sampling, exposure assessment and end-of-life controls; binder encapsulation is not a substitute for release testing.',detail:'This case provides evidence for a local masonry route under the reported test conditions. Durability, production quality assurance and mercury behaviour over the product lifecycle need further work.',sourceState:"The tested bricks met non-loadbearing masonry standards, with compressive strengths of 5.02–13.3 MPa and total mercury of 0.03–0.10 mg/kg.",sources:[{label:'Cleaner Waste Systems (2025)',url:'https://doi.org/10.1016/j.clwas.2025.100269'}],lastReviewed:'23 September 2026'},
  {id:'ecuador-blocks',title:'Southern Ecuador gold tailings in concrete blocks',location:'Portovelo–Zaruma, Ecuador',region:'South America',material:'Tailings',commodity:'Gold',waste:'Gold-processing tailings',pathway:'Construction',stage:'Laboratory',readiness:'Conditional',evidence:'Peer-reviewed study',lat:-3.72,lng:-79.62,summary:'Gold tailings were assessed as a partial sand substitute in concrete-block manufacture.',technical:'Physical, chemical and mineralogical characterisation was combined with EN 12457-2 leaching and block testing at 50% and 70% sand replacement. The blocks passed the reported leaching criteria but did not meet the cited compressive-strength and absorption requirements.',environmental:'The study reported leach-test results within its stated criteria under the tested conditions; exposure-specific and long-term release testing would still be required.',detail:'A useful negative-to-conditional result linking environmental and product testing. The authors recommended testing mixtures below 50% tailings rather than treating the reported blocks as compliant products.',sourceState:"Blocks replacing 50% or 70% of sand passed the reported leaching criteria, but their compressive strength and absorption did not meet the applicable regulations.",sources:[{label:'Sustainability (2022)',url:'https://doi.org/10.3390/su142316285'}],lastReviewed:'23 September 2026'},
  {id:'wa-geopolymer-bricks',title:'WA iron-ore tailings geopolymer bricks',location:'Western Australia, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Iron ore',waste:'Iron-ore tailings',pathway:'Construction',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:-25.5,lng:118.5,summary:'Western Australian iron-ore tailings were used as the principal feedstock in alkali-activated geopolymer bricks.',technical:'The study reported XRD, activator and curing optimisation, compressive strength, absorption, durability and an indicative cost assessment. Peak strength exceeded 50 MPa.',environmental:'Avoiding kiln firing can reduce thermal demand, but activator manufacture, caustic handling and leachability must be included in whole-of-life assessment.',detail:'A prominent Australian laboratory case with high reported mechanical performance. Pilot production, durability exposure and reagent economics remain gates.',sourceState:"The optimum geopolymer brick reached 50.53 MPa unconfined compressive strength and met the cited Australian and ASTM brick requirements.",sources:[{label:'International Journal of Mining, Reclamation and Environment',url:'https://doi.org/10.1080/17480930.2014.993834'}],lastReviewed:'23 September 2026'},
  {id:'pico-block-factory',title:'Mina do Pico tailings block factory',location:'Itabirito, Minas Gerais, Brazil',region:'South America',material:'Tailings',commodity:'Iron ore',waste:'Silica-rich iron-ore tailings',pathway:'Construction',stage:'Operating demonstration',readiness:'Operating evidence',evidence:'Company operating disclosure',lat:-20.25,lng:-43.8,summary:'Vale operates a block plant that converts sandy iron-ore tailings into interlocking pavers and other precast products.',technical:'The plant converts silica-rich iron-ore tailings into precast products. Vale reported more than 407,000 interlocking pavers produced during 2025.',environmental:'Substitution for natural sand and avoided storage are potential benefits. Public disclosure does not replace independent product, leaching or lifecycle verification.',detail:'A current industrial demonstration of tailings entering conventional construction products. The production figures are operator-reported and have not been independently verified here.',sourceState:"Vale reports that the Pico plant has converted tailings into interlocking pavers since 2021 and produced more than 407,000 pavers in 2025.",sources:[{label:'Vale project announcement',url:'https://www.vale.com/pt/w/vale-opens-factory-that-transforms-mining-waste-into-products-for-civil-construction'}],lastReviewed:'23 September 2026'},
  {id:'donimalai-bricks',title:'Donimalai iron tailings masonry units',location:'Karnataka, India',region:'Asia-Pacific',material:'Tailings',commodity:'Iron ore',waste:'Beneficiation tailings',pathway:'Construction',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:15.094,lng:76.549,summary:'Donimalai tailings were tested with cement, sand and sodium silicate in brick formulations.',technical:'Formulation work examined tailings content and binder combinations against strength and water-absorption requirements.',environmental:'Binder intensity and tailings chemistry determine net benefit; regulated-element release and durability require project-specific testing.',detail:'The work supports further development of unfired masonry units using this iron tailings stream. It remains a laboratory precedent rather than a commercial product record.',sourceState:"The 8:2 tailings-to-cement mix reached 8.58 MPa, while the more economical 9:1 mix complied with the cited Indian brick standard.",sources:[{label:'CSIR-NIScPR research record',url:'https://nopr.niscpr.res.in/handle/123456789/56477'}],lastReviewed:'23 September 2026'},
  {id:'wa-shotcrete',title:'WA tailings and waste rock in mine shotcrete',location:'Western Australia, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Multiple commodities',waste:'Tailings and crushed waste rock',pathway:'Construction',stage:'Research programme',readiness:'Research required',evidence:'Government-funded research',lat:-31.95,lng:115.86,summary:'A University of Western Australia programme is investigating mine wastes as aggregate and partial binder inputs for underground shotcrete.',technical:'The programme targets aggregate replacement and reduced Portland-cement demand while retaining early strength, support performance and constructability.',environmental:'Potential benefits include reduced virgin aggregate demand and waste stabilisation; underground exposure, rebound, pumping and leaching need validation.',detail:'An Australian pathway-development case rather than a completed product demonstration. Underground support could create an on-site market with lower transport burden.',sourceState:"The funded project aims to replace conventional shotcrete aggregate with tailings and waste rock and to reduce cement demand; the project page does not report performance results.",sources:[{label:'Minerals Research Institute of WA project',url:'https://www.mriwa.wa.gov.au/research-projects/project-portfolio/investigating-the-utilisation-of-mine-tailings-and-waste-rock-in-the-shotcrete-for-underground-support/'}],lastReviewed:'23 September 2026'},
  {id:'shuangqi-glass-ceramic',title:'Shuangqi gold tailings glass-ceramics',location:'Shandong, China',region:'Asia-Pacific',material:'Tailings',commodity:'Gold',waste:'Gold tailings',pathway:'Industrial materials',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:36.4,lng:118.0,summary:'Gold tailings were used at high content in dense glass-ceramics produced through controlled heat treatment.',technical:'Phase development, density, Vickers hardness, flexural strength and microstructure were assessed; the 60 wt% formulation achieved strong reported properties.',environmental:'High tailings use is attractive, but melting and heat treatment are energy intensive; contaminant partitioning and product end-of-life require assessment.',detail:'The study demonstrates a high-value ceramic route. Commercial feasibility depends on energy, additives, feed consistency and proximity to ceramic manufacturing.',sourceState:"At 60 wt% tailings and 950°C for two hours, the glass-ceramic reached 116 MPa flexural strength and 8.17 GPa hardness.",sources:[{label:'RSC Advances (2022)',url:'https://doi.org/10.1039/D2RA01012G'}],lastReviewed:'23 September 2026'},
  {id:'finland-lithium-ceramics',title:'Spodumene tailings in building ceramics',location:'Oulu, Finland',region:'Europe',material:'Tailings',commodity:'Lithium',waste:'Quartz–feldspar spodumene tailings',pathway:'Industrial materials',stage:'Laboratory',readiness:'Lab feasibility',evidence:'Peer-reviewed study',lat:65.01,lng:25.47,summary:'Quartz–feldspar tailings and waste glass wool were co-processed into high-performance ceramic specimens.',technical:'XRD/Rietveld, thermal analysis, microscopy, density, absorption and mechanical testing were used across 750–950°C sintering conditions.',environmental:'Co-utilisation of two waste streams and lower-temperature densification are promising; thermal energy and feed cleanliness remain important.',detail:'The work reported ceramic properties meeting cited ASTM C62 requirements. It is a laboratory example of tailoring flux behaviour to improve performance.',sourceState:"The tailings and glass-wool ceramics met ASTM C62 requirements and reached 90 MPa compressive strength and 25 MPa flexural strength.",sources:[{label:'Journal of Building Engineering / Oulu repository',url:'https://oulurepo.oulu.fi/handle/10024/32367'}],lastReviewed:'23 September 2026'},
  {id:'century-zinc',title:'Century zinc tailings retreatment',location:'Lower Gulf, Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Zinc–lead–silver',waste:'Historic flotation tailings',pathway:'Metals recovery',stage:'Operating / care cycles',readiness:'Commercial',evidence:'Operator and government disclosures',lat:-18.73,lng:138.6,summary:'A large-scale hydraulic mining and flotation operation recovers zinc from the former Century Mine tailings deposit.',technical:'Hydraulic reclamation, slurry transport and conventional flotation use substantial existing mine and port infrastructure; operations began on tailings in 2018.',environmental:'Retreatment can support progressive rehabilitation, but water balance, geotechnical change and residual-tailings closure remain core controls.',detail:'Australia’s most prominent commercial tailings-recovery example. It demonstrates that grade, scale and inherited infrastructure can make secondary mining competitive.',sourceState:"The operator describes Century as Australia's largest tailings retreatment operation and reports hydraulic re-mining of the zinc-bearing tailings storage facility.",sources:[{label:'Sibanye-Stillwater Century operation',url:'https://www.sibanyestillwater.com/business/australia/century/'},{label:'Queensland Government announcement',url:'https://statements.qld.gov.au/statements/88174'}],lastReviewed:'23 September 2026'},
  {id:'mount-morgan',title:'Mount Morgan tailings processing and rehabilitation',location:'Mount Morgan, Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Gold–copper',waste:'Historic mine tailings',pathway:'Metals recovery',stage:'Financed development',readiness:'Development',evidence:'Australian government project disclosure',lat:-23.65,lng:150.39,summary:'The project is designed to recover value from historic tailings while funding rehabilitation of a major legacy mine site.',technical:'The development combines tailings reprocessing with new rehabilitation infrastructure; public information emphasises project integration rather than detailed metallurgy.',environmental:'The proposition is tied to removal and treatment of legacy material and long-term rehabilitation. Outcomes depend on execution and residuals management.',detail:'A high-profile Australian example linking secondary recovery with legacy-liability reduction. Technical and schedule claims should be tracked against future operating data.',sourceState:"NAIF reports financial close on a loan of up to A$66 million for a project intended to recover gold and copper while rehabilitating the legacy mine site.",sources:[{label:'Northern Australia Infrastructure Facility',url:'https://www.naif.gov.au/our-projects/heritage-minerals-mount-morgan-tailings-processing-and-rehabilitation-project/'}],lastReviewed:'23 September 2026'},
  {id:'hellyer',title:'Hellyer polymetallic tailings reprocessing',location:'Western Tasmania, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Gold–silver–lead–zinc',waste:'Historic polymetallic tailings',pathway:'Metals recovery',stage:'Operating history',readiness:'Commercial precedent',evidence:'Company and public disclosures',lat:-41.57,lng:145.72,summary:'The Hellyer facility has reprocessed legacy polymetallic tailings to produce precious- and base-metal concentrates.',technical:'Fine-grained complex sulphide tailings require controlled regrinding, flotation and concentrate management; operating history provides a useful precedent.',environmental:'Retreatment changes the legacy deposit and creates new residuals. Acid-forming potential, water management and final closure remain key.',detail:'Hellyer illustrates both the value and complexity of secondary mining from polymetallic tailings. Public technical details and project status require periodic review.',sourceState:"Tasmania's EPA reported that tailings reprocessing began in 2018 to produce lead, zinc and pyrite concentrates, with residual tailings placed in a new storage facility.",sources:[{label:'Tasmanian EPA Annual Report 2018–19',url:'https://epa.tas.gov.au/Documents/EPA%20Annual%20Report%202018-19.pdf'}],lastReviewed:'23 September 2026'},
  {id:'ergo',title:'Ergo gold tailings retreatment',location:'Gauteng, South Africa',region:'Africa',material:'Tailings',commodity:'Gold',waste:'Historic gold tailings',pathway:'Metals recovery',stage:'Operating',readiness:'Commercial',evidence:'Operator disclosure',lat:-26.25,lng:28.15,summary:'Historic Witwatersrand tailings are reclaimed and treated through a large surface gold-recovery network.',technical:'Reclamation, repulping, screening, classification, milling and carbon-in-leach processing are integrated across legacy deposits and regional infrastructure.',environmental:'Consolidation and retreatment can remove old dumps, but dust, water, uranium-bearing residues and deposition of new tailings require continuing control.',detail:'A long-running commercial benchmark for re-mining historic gold residues. Success is strongly linked to very large inventory, infrastructure and metallurgical know-how.',sourceState:"DRDGOLD reports that Ergo hydraulically reclaims historic slimes and treats them through screening, classification, milling and carbon-in-leach recovery.",sources:[{label:'DRDGOLD Ergo operation',url:'https://www.drdgold.com/our-business/ergo'}],lastReviewed:'23 September 2026'},
  {id:'mvc-chile',title:'El Teniente tailings copper recovery',location:'Rancagua, Chile',region:'South America',material:'Tailings',commodity:'Copper–molybdenum',waste:'Fresh and historic concentrator tailings',pathway:'Metals recovery',stage:'Operating',readiness:'Commercial',evidence:'Operator disclosure',lat:-34.17,lng:-70.74,summary:'Minera Valle Central recovers copper and molybdenum from fresh El Teniente tailings and historic deposits.',technical:'Fresh tailings are diverted for treatment; historic material is hydraulically reclaimed, classified, ground and floated with water recovery integrated.',environmental:'Secondary recovery improves resource efficiency, while hydraulic reclamation and redeposition require water, stability and closure controls.',detail:'A major international benchmark operating since the 1990s. It demonstrates sustained recovery where residual grade, throughput and access to an existing stream align.',sourceState:"MVC states that it processes all fresh El Teniente tailings and also hydraulically reclaims historic tailings to produce copper and molybdenum concentrates.",sources:[{label:'Minera Valle Central process',url:'https://mineravallecentral.cl/queprocesamos/'}],lastReviewed:'23 September 2026'},
  {id:'missouri-cobalt',title:'Missouri cobalt and nickel tailings recovery',location:'Fredericktown, Missouri, USA',region:'North America',material:'Tailings',commodity:'Cobalt–nickel–copper',waste:'Legacy metallurgical tailings',pathway:'Metals recovery',stage:'Demonstration / redevelopment',readiness:'Conditional',evidence:'Institutional case study',lat:37.56,lng:-90.29,summary:'Legacy tailings were evaluated and reprocessed for cobalt-bearing and nickel-bearing concentrates alongside closure works.',technical:'The case combines secondary-resource recovery with characterisation, processing and capping of remaining material.',environmental:'Recovery can reduce a legacy inventory, but the balance between concentrate production, residual chemistry and final cover performance controls net benefit.',detail:'An institutional case showing how critical-mineral recovery can be paired with remediation. Public performance data are more limited than for mature operators.',sourceState:"ITRC reports that a tailings processing facility was built in 2019 to recover cobalt-bearing concentrates before sampling and covering the remaining material.",sources:[{label:'ITRC Mine Waste case studies',url:'https://mw-1.itrcweb.org/project-summaries-and-case-studies/'}],lastReviewed:'23 September 2026'},
  {id:'pine-creek-miwatch',title:'Pine Creek secondary critical-mineral prospectivity',location:'Pine Creek, Northern Territory, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Gold–silver and critical metals',waste:'Historic tailings and mine waste',pathway:'Metals recovery',stage:'Characterisation',readiness:'Research required',evidence:'Geological survey programme',lat:-13.82,lng:131.84,summary:'Government-led sampling is assessing historic Pine Creek wastes as potential secondary resources for critical and precious metals.',technical:'Geochemistry and mineralogy identify metal deportment and candidate recovery routes including flotation, gravity, cyanidation and bioleaching.',environmental:'This is prospectivity work, not a recovery project. Any pathway must integrate acid-forming minerals, arsenic and rehabilitation outcomes.',detail:'A strong Australian characterise-first case. The Cosmo work identified anomalous metals and host minerals, but resource definition, recovery testing and economics remain gates.',sourceState:"The first-pass Cosmo study found anomalous silver, gold and arsenic and proposed flotation, gravity, cyanidation and bioleaching for further investigation.",sources:[{label:'Northern Territory Geological Survey',url:'https://resourcingtheterritory.nt.gov.au/news-and-events/news/2025/secondary-prospectivity-studies-continue-in-the-pine-creek-region'}],lastReviewed:'23 September 2026'},
  {id:'kunwarara-magnesium',title:'Kunwarara tailings to magnesium feedstock',location:'Kunwarara, Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Magnesite',waste:'Fine magnesite-beneficiation tailings',pathway:'Metals recovery',stage:'Research and development',readiness:'Research required',evidence:'Queensland Government programme',lat:-22.93,lng:149.33,summary:'QMAG is characterising fine tailings for fractions suitable for high-purity magnesium chloride and magnesium-metal production.',technical:'The programme combines feed characterisation, fraction selection and process testing for an electrolytic magnesium route.',environmental:'Potential value depends on purification yield, reagent and energy demand, brine/residue management and comparison with conventional production.',detail:'An emerging Australian critical-minerals pathway with government support. It is included as development evidence; no commercial recovery claim is made.',sourceState:"The Queensland program will characterise and test fine magnesite tailings to identify fractions suitable for high-purity magnesium-chloride feedstock.",sources:[{label:'Business Queensland programme',url:'https://www.business.qld.gov.au/industries/mining-energy-water/resources/geoscience-information/exploration-incentives/collaborative-development-program'}],lastReviewed:'23 September 2026'},
  {id:'kidston-revegetation',title:'Kidston direct tailings revegetation',location:'North Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Gold',waste:'Gold tailings',pathway:'Land restoration',stage:'Field demonstration',readiness:'Site-specific demonstration',evidence:'Conference case study',lat:-18.87,lng:144.14,summary:'Field work assessed whether the tailings surface could support vegetation directly without a conventional soil cap.',technical:'Earlier trials and site assessment examined physical substrate behaviour, plant establishment and conditions supporting direct revegetation.',environmental:'Avoiding imported cover soil can reduce disturbance, but erosion, rooting depth, salinity, geochemistry and long-term ecosystem trajectory are site-specific.',detail:'An important Australian closure precedent because the tailings themselves form part of the rehabilitated landform. It should not be generalised to reactive residues.',sourceState:"The paper reports that alkaline tailings supported native trees and shrubs without a soil cap when establishment included initial irrigation and fertilisation.",sources:[{label:'Australian Centre for Geomechanics paper',url:'https://papers.acg.uwa.edu.au/p/605_30_Mulligan/'}],lastReviewed:'23 September 2026'},
  {id:'sudbury-technosol',title:'Sudbury amended-tailings Technosols',location:'Sudbury, Ontario, Canada',region:'North America',material:'Tailings',commodity:'Nickel–copper',waste:'Acid-generating and neutral tailings',pathway:'Land restoration',stage:'Growth-chamber study',readiness:'Research required',evidence:'Peer-reviewed study',lat:46.49,lng:-80.99,summary:'Mine residuals were blended with pulp-and-paper residues and forest humus to create plant-growth substrates.',technical:'The study measured substrate chemistry, microbial communities, germination and biomass in both acid-producing and neutral-to-alkaline tailings.',environmental:'Organic amendments improved nutrient status and raised pH in acid tailings, but field persistence, supply and contaminant uptake require verification.',detail:'A circular rehabilitation concept combining regional residual streams. Controlled work supports biological feasibility; field hydrology and long-term geochemistry remain unresolved.',sourceState:"Organic amendments increased pH, germination and plant growth, but soluble copper and nickel also increased in some amended substrates.",sources:[{label:'Science of the Total Environment / PubMed',url:'https://pubmed.ncbi.nlm.nih.gov/30212679/'}],lastReviewed:'23 September 2026'},
  {id:'coal-technosol-sa',title:'Fine-coal tailings Technosols',location:'Mpumalanga, South Africa',region:'Africa',material:'Tailings',commodity:'Coal',waste:'Fine coal processing waste',pathway:'Land restoration',stage:'Laboratory / greenhouse',readiness:'Research required',evidence:'Water Research Commission programme',lat:-26.0,lng:29.2,summary:'Fine coal wastes and organic amendments were evaluated as engineered soils for mine-site rehabilitation.',technical:'Characterisation, coal recovery, amendment optimisation, microbial stimulation and plant-growth response formed the proof-of-concept programme.',environmental:'The route can reduce topsoil demand and recover residual coal, but sulphur, salinity, residual reagents and field erosion remain controls.',detail:'A useful full-volume mine-site reuse concept. Evidence supports field validation rather than immediate specification as a general-purpose rehabilitation soil.',sourceState:"The report found one ultrafine coal-waste stream unsuitable for soil manufacture, while two other streams supported coal recovery and experimental Technosol development.",sources:[{label:'South African Water Research Commission',url:'https://www.wrc.org.za/wp-content/uploads/mdocs/2844%20final.pdf'}],lastReviewed:'23 September 2026'},
  {id:'wheal-jane',title:'Wheal Jane mine-water treatment',location:'Cornwall, United Kingdom',region:'Europe',material:'Mine water',commodity:'Tin–copper–zinc',waste:'Acidic metal-bearing mine water',pathway:'Water treatment',stage:'Operating',readiness:'Commercial treatment',evidence:'Government case study',lat:50.241,lng:-5.054,summary:'A long-running active scheme manages high-flow contaminated water from the former mine after passive pilot trials.',technical:'The system uses lime dosing, aeration, high-density sludge recirculation, clarification and continuous monitoring; passive lagoons were also trialled.',environmental:'The case demonstrates metals removal but also the land and flow limitations of passive systems and the need to manage treatment sludge.',detail:'An environmental-management benchmark showing why treatment selection must follow flow, chemistry, space and residuals. It is not presented as material reuse.',sourceState:"The operating scheme treats about 5.6 million cubic metres of mine water annually using lime dosing, aeration, sludge recirculation and clarification.",sources:[{label:'UK Environment Agency case study',url:'https://www.gov.uk/government/case-studies/wheal-jane-mine-water-treatment-scheme'}],lastReviewed:'23 September 2026'},
  {id:'finland-reactive-barrier',title:'Tailings-containing adsorbents screened for mine-water treatment',location:'Northern Finland',region:'Europe',material:'Tailings',commodity:'Nickel',waste:'Tailings in alkali-activated media',pathway:'Water treatment',stage:'Laboratory screening',readiness:'Research required',evidence:'Peer-reviewed laboratory and pilot study',lat:66.5,lng:26.0,summary:'Mine-tailings-containing alkali-activated adsorbents were screened in laboratory tests, but the field pilot used a slag-only formulation.',technical:'The study compared metakaolin, slag, mine tailings and zeolite formulations. The selected 0.5 m³/day field-pilot material contained blast-furnace slag only, so it did not demonstrate tailings reuse at pilot scale.',environmental:'Media stability, saturation, regeneration or disposal and release of bound constituents govern lifecycle performance.',detail:'The study supports continued laboratory investigation of tailings-containing adsorbents. It does not support a claim that tailings-derived media were proven in the field pilot.',sourceState:"Mine-tailings-containing adsorbents were screened in laboratory work, but the one-week field pilot used the selected slag-only adsorbent rather than a tailings-containing formulation.",sources:[{label:'International Journal of Environmental Science and Technology',url:'https://link.springer.com/article/10.1007/s13762-024-06002-y'}],lastReviewed:'23 September 2026'},
  {id:'mount-keith-carbon',title:'Mount Keith nickel-tailings carbonation',location:'Western Australia, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Nickel',waste:'Ultramafic nickel tailings',pathway:'Carbon mineralisation',stage:'Field research / pilot',readiness:'Field evidence',evidence:'Peer-reviewed and institutional research',lat:-27.26,lng:120.55,summary:'Weathering of reactive ultramafic tailings forms stable carbonate minerals, with field programmes examining acceleration and verification.',technical:'Mineralogy, carbonate formation, pore-water chemistry and field flux measurements underpin the work; handling can expose fresh reactive surfaces.',environmental:'Mineral storage is potentially durable and may aid stabilisation, but MRV, water chemistry, dust and acceleration energy must be included.',detail:'A globally significant Australian natural-laboratory case. Passive uptake is observed; the challenge is to increase rate while proving additionality and permanence.',sourceState:"The model reproduced carbonate minerals observed in ten-year-old tailings and estimated passive carbon uptake of 0.6–1 kg CO₂ per square metre per year.",sources:[{label:'CSIRO mineral carbonation overview',url:'https://www.csiro.au/en/news/All/Articles/2023/July/mineral-carbonation-symposium'},{label:'Vadose Zone Journal field study',url:'https://doi.org/10.2136/vzj2011.0053'}],lastReviewed:'23 September 2026'},
  {id:'crawford-carbonation',title:'Crawford in-process tailings carbonation',location:'Timmins, Ontario, Canada',region:'North America',material:'Tailings',commodity:'Nickel',waste:'Ultramafic nickel tailings',pathway:'Carbon mineralisation',stage:'Pilot / project development',readiness:'Pilot evidence',evidence:'Government-funded project',lat:48.48,lng:-81.33,summary:'A pilot programme is integrating CO₂ mineralisation into the proposed nickel process and tailings circuit.',technical:'The project targets accelerated reaction of CO₂ with reactive ultramafic minerals and verification of storage stability and permanence.',environmental:'The route promises permanent mineral storage, but claimed scale depends on mine development, process integration and robust MRV.',detail:'A leading example of designing carbonation into a future process. Commercial claims remain contingent on full project delivery and independent verification.',sourceState:"The active government-funded project aims to demonstrate pilot-scale storage and permanence; future million-tonne claims depend on the proposed mine becoming operational.",sources:[{label:'Natural Resources Canada project',url:'https://natural-resources.canada.ca/funding-partnerships/novel-carbon-storage-solution-through-critical-minerals-production-process-tailings-carbonation'}],lastReviewed:'23 September 2026'},
  {id:'sco2ut-canada',title:'SCO2UT ultramafic-tailings field research',location:'British Columbia and Canadian mine sites',region:'North America',material:'Tailings',commodity:'Nickel and diamond',waste:'Ultramafic mine tailings',pathway:'Carbon mineralisation',stage:'Field research',readiness:'Research required',evidence:'University–industry programme',lat:53.7,lng:-122.6,summary:'A multi-site programme investigates accelerated carbon mineralisation and verification methods across different residues and climates.',technical:'The work considers mineralogy, comminution, deposition, climate, gas concentration and operational integration rather than one universal process.',environmental:'Potential co-benefits include dust mitigation and metal immobilisation; each site still requires water-quality and geochemical assessment.',detail:'This landscape case shows why carbonation performance cannot be transferred by commodity name alone. It provides methods and field trials rather than a commercial claim.',sourceState:"The research program is testing ways to accelerate carbon mineralisation, verify storage stability and integrate field trials into mine operations.",sources:[{label:'UBC MDRU SCO2UT programme',url:'https://www.mdru.ubc.ca/projects/co2-sequestration/'}],lastReviewed:'23 September 2026'},
  {id:'brazil-road-section',title:'Iron tailings in an experimental pavement section',location:'Congonhas, Minas Gerais, Brazil',region:'South America',material:'Tailings',commodity:'Iron ore',waste:'Iron-ore tailings and waste rock',pathway:'Construction',stage:'Field demonstration',readiness:'Conditional demonstration',evidence:'Peer-reviewed field study',lat:-20.5,lng:-43.86,summary:'Tailings, waste rock and iron-ore canga were placed in base and sub-base mixtures in a monitored experimental road section.',technical:'Laboratory validation informed two field mixtures: 35% tailings with waste rock and canga in the base, and 35% tailings with graded aggregates in the sub-base. Field response exposed deformation sensitivity in the sub-base.',environmental:'Large-volume road use can displace quarried material, but drainage, dust, geochemistry and long-term deformation must be controlled. The field result shows why laboratory compliance alone is insufficient.',detail:'A valuable field-scale counterpoint to laboratory pavement studies. The trial demonstrated constructability while identifying sub-base deformation as a limiting behaviour requiring mix and layer redesign.',sourceState:"The 35% tailings mixtures behaved differently in the field, and cracking and deformation appeared within a year; the authors recommend more conservative proportions.",sources:[{label:'REM: International Engineering Journal (2022)',url:'https://www.scielo.br/j/remi/a/47sKMLYmBKsKf6jLwMtL3sr/?lang=en'}],lastReviewed:'23 September 2026'},
  {id:'tanami-paste-backfill',title:'Tanami gold-tailings cemented paste backfill',location:'Northern Territory, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Gold',waste:'Excavated gold tailings',pathway:'Backfill',stage:'Operating improvement',readiness:'Commercial operation',evidence:'Australian mine case study',lat:-20.45,lng:129.71,summary:'Dry excavated tailings are conditioned and pumped underground as cemented paste backfill at the Tanami gold operation.',technical:'Sampling, laboratory testing and site trials examined variability in chemistry, fineness and clay content. These factors affected solids concentration and pipeline pressure. They also constrained throughput and strength consistency.',environmental:'Returning tailings underground can reduce surface storage demand and support extraction, but binder emissions, water balance, barricade safety and retained underground contaminants remain design controls.',detail:'An operating Australian example where tailings variability directly affected backfill rheology and binder demand. The case shows that backfill is a designed ground-support product, not simply a disposal route.',sourceState:"The case study reports that a chemical admixture increased solids content, reduced pipeline pressure and improved throughput and strength consistency for excavated tailings paste.",sources:[{label:'Australian Centre for Geomechanics case study',url:'https://papers.acg.uwa.edu.au/p/1504_28_Salter/'}],lastReviewed:'23 September 2026'},
  {id:'bowen-coal-critical-minerals',title:'Bowen Basin coal-tailings critical-mineral study',location:'Bowen Basin, Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Metallurgical and thermal coal',waste:'Coal mine tailings',pathway:'Metals recovery',stage:'Regional study',readiness:'Early research',evidence:'Queensland Government-funded programme',lat:-22.2,lng:148.2,summary:'A regional programme is examining rare earths, vanadium and broader value-recovery options in coal mine tailings across the Bowen Basin.',technical:'The funded work is intended to characterise multiple waste streams and screen recovery and full-volume reuse pathways with participating producers and research partners.',environmental:'No recovery performance is yet established publicly. Future assessment must address grade variability, process water, residual carbon, secondary wastes and whole-volume outcomes.',detail:'An emerging Australian portfolio case included to distinguish funded prospectivity from demonstrated recovery. Public evidence currently supports the research programme, not a commercial resource claim.',sourceState:"The A{id:'bowen-coal-critical-minerals',title:'Bowen Basin coal-tailings critical-mineral study',location:'Bowen Basin, Queensland, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Metallurgical and thermal coal',waste:'Coal mine tailings',pathway:'Metals recovery',stage:'Regional study',readiness:'Early research',evidence:'Queensland Government-funded programme',lat:-22.2,lng:148.2,summary:'A regional programme is examining rare earths, vanadium and broader value-recovery options in coal mine tailings across the Bowen Basin.',technical:'The funded work is intended to characterise multiple waste streams and screen recovery and full-volume reuse pathways with participating producers and research partners.',environmental:'No recovery performance is yet established publicly. Future assessment must address grade variability, process water, residual carbon, secondary wastes and whole-volume outcomes.',detail:'An emerging Australian portfolio case included to distinguish funded prospectivity from demonstrated recovery. Public evidence currently supports the research programme, not a commercial resource claim.',.5 million study will examine rare earths, vanadium and other recovery pathways in Bowen Basin coal tailings; it does not yet report recovery results.",sources:[{label:'Queensland Government programme announcement',url:'https://statements.qld.gov.au/statements/104125'}],lastReviewed:'23 September 2026'},
  {id:'nsw-mine-reuse',title:'NSW mine-waste critical-mineral characterisation',location:'Regional New South Wales, Australia',region:'Asia-Pacific',material:'Tailings',commodity:'Copper, cobalt, silver, antimony and base metals',waste:'Historic tailings, waste rock and processing residues',pathway:'Metals recovery',stage:'State-wide characterisation',readiness:'Prospectivity evidence',evidence:'Geological Survey of NSW programme',lat:-32.2,lng:147.2,summary:'More than 1,200 samples from 28 mine sites and one power-station site were screened for critical minerals and high-tech metals.',technical:'High-precision chemical analysis identified elevated concentrations across sites including CSA, Great Cobar, Nymagee, Endeavour and Hillgrove; mineral deportment and recovery testing remain site-level next steps.',environmental:'Elevated concentration is not recoverability. Any secondary-mining proposal must integrate acid-generating potential, contaminated-site obligations and rehabilitation of remaining material.',detail:'A strong Australian precompetitive dataset showing how systematic characterisation can identify secondary prospectivity without overstating commercial readiness.',sourceState:"The program analysed more than 1,200 samples from 28 mine sites and found elevated concentrations of 11 critical minerals, including copper, cobalt, silver and antimony.",sources:[{label:'NSW Resources Mine Reuse Project',url:'https://www.resources.nsw.gov.au/geological-survey/projects/mine-reuse-project'}],lastReviewed:'23 September 2026'}
];

const PATHWAY_META={
  'Construction':{slug:'construction',code:'CO'},
  'Metals recovery':{slug:'metals-recovery',code:'MR'},
  'Backfill':{slug:'backfill',code:'BF'},
  'Land restoration':{slug:'land-restoration',code:'LR'},
  'Water treatment':{slug:'water-treatment',code:'WT'},
  'Carbon mineralisation':{slug:'carbon-mineralisation',code:'CM'},
  'Industrial materials':{slug:'industrial-materials',code:'IM'}
};
const REGION_ORDER=['Africa','Asia-Pacific','Europe','North America','South America'];
const MATURITY_LEVELS=['Concept','Laboratory','Pilot','Demonstration','Operating'];
const TRANSFER_QUESTIONS={
  'Construction':'Does the site-specific residue meet durability, leaching, production-control and applicable material-specification requirements at the proposed scale?',
  'Metals recovery':'Do grade variability, mineral deportment, recovery, reagent demand and residual-waste management support a viable site-specific flowsheet?',
  'Backfill':'How will residue variability affect rheology, binder demand, strength development, reticulation and underground environmental controls?',
  'Land restoration':'Will the amended material sustain vegetation while controlling erosion, pore-water quality and contaminant exposure over the required timeframe?',
  'Water treatment':'Can treatment performance, media life, hydraulic behaviour and spent-material management be demonstrated under representative field conditions?',
  'Carbon mineralisation':'Can additional, durable carbon uptake be measured and verified without creating unacceptable energy, water or environmental burdens?',
  'Industrial materials':'Can feed consistency, processing demand, product durability, release behaviour and market specifications be controlled beyond laboratory batches?'
};
const BENEFIT_LENSES={
  'Construction':{
    value:'Potential co-product revenue, reduced demand for virgin aggregate or binder inputs, local supply and avoided tailings storage.',
    constraints:'Product specification, consistency, processing and binder demand, customer qualification, market volume, haulage distance and residual liability.'
  },
  'Metals recovery':{
    value:'Recovered metal revenue, critical-mineral supply, improved resource efficiency and possible reduction of a legacy or active tailings inventory.',
    constraints:'Representative grade, mineral deportment, recovery, throughput, reagents, energy, CAPEX, commodity price and management of the reprocessed residue.'
  },
  'Backfill':{
    value:'Reduced surface deposition, substitution for purchased fill, potential storage-capacity benefit and integration with underground support or closure.',
    constraints:'Binder cost, rheology, pumping and reticulation, strength, production continuity, water balance and underground environmental performance.'
  },
  'Land restoration':{
    value:'Closure and rehabilitation outcomes, reduced erosion or exposure, improved land use and possible avoidance of imported rehabilitation materials.',
    constraints:'Long-term geochemistry, soil function, vegetation performance, water quality, monitoring duration and whether treatment changes the underlying liability.'
  },
  'Water treatment':{
    value:'Potential value includes water recovery, a reduced discharge burden and support for compliance. Some projects may also recover metals or useful treatment products when the evidence supports that outcome.',
    constraints:'Flow and chemistry variability, consumables, energy, plant reliability, sludge or spent-media management and long-term treatment obligations.'
  },
  'Carbon mineralisation':{
    value:'Durable carbon removal, possible carbon value, improved residue stability and a measurable decarbonisation contribution.',
    constraints:'Additional uptake, kinetics, measurement and verification, energy, water, land, operating integration and the permanence of storage.'
  },
  'Industrial materials':{
    value:'Co-product revenue, reduced waste handling, substitution for virgin industrial feedstocks and diversified regional material supply.',
    constraints:'Feed consistency, processing intensity, quality assurance, durability, regulated constituents, market size, logistics and customer acceptance.'
  }
};
const cards=document.querySelector('#cards'),count=document.querySelector('#result-count'),search=document.querySelector('#search'),region=document.querySelector('#region'),material=document.querySelector('#material'),pathway=document.querySelector('#pathway'),modal=document.querySelector('#detail-modal'),mapPreview=document.querySelector('#map-preview'),mapTooltip=document.querySelector('#map-tooltip'),showMoreButton=document.querySelector('#show-more-cases'),paginationStatus=document.querySelector('#case-pagination-status');
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const pathwayMeta=value=>PATHWAY_META[value]||{slug:String(value).toLowerCase().replace(/[^a-z]+/g,'-'),code:'RP'};
const maturityFor=caseItem=>{
  const value=`${caseItem.stage} ${caseItem.readiness}`.toLowerCase();
  if(/operating|commercial operation/.test(value))return 'Operating';
  if(/demonstration|commissioned|field trial/.test(value))return 'Demonstration';
  if(/pilot/.test(value))return 'Pilot';
  if(/laboratory|lab feasibility/.test(value))return 'Laboratory';
  return 'Concept';
};
const recordURL=id=>`${window.location.origin}/technical-library/cases/${encodeURIComponent(id)}/`;
const CASE_BATCH_SIZE=9;
let mapProjection=null,selectedCaseId=CASES[0]?.id||null,visibleLimit=CASE_BATCH_SIZE;

function showCase(id){
  const c=CASES.find(item=>item.id===id); if(!c||!modal)return;
  document.querySelector('#modal-title').textContent=c.title;
  document.querySelector('#modal-location').textContent=c.location;
  document.querySelector('#modal-text').textContent=c.detail;
  document.querySelector('#modal-material').textContent=`${c.commodity} · ${c.waste}`;
  document.querySelector('#modal-pathway').textContent=c.pathway;
  document.querySelector('#modal-evidence').textContent=c.evidence;
  document.querySelector('#modal-stage').textContent=c.stage;
  document.querySelector('#modal-maturity').textContent=maturityFor(c);
  document.querySelector('#modal-readiness').textContent=c.readiness;
  document.querySelector('#modal-source-state').textContent=c.sourceState;
  const evidenceLink=document.querySelector('#modal-source-link');
  evidenceLink.href=c.sources[0].url;
  evidenceLink.textContent=`Verify in ${c.sources[0].label} ↗`;
  document.querySelector('#modal-technical').textContent=c.technical;
  document.querySelector('#modal-environmental').textContent=c.environmental;
  const benefit=BENEFIT_LENSES[c.pathway]||{value:'Potential product, avoided-cost, risk-reduction or strategic value should be defined against the site baseline.',constraints:'Quantify material variability, process requirements, market demand, logistics, approvals and residual liability.'};
  document.querySelector('#modal-benefit').textContent=benefit.value;
  document.querySelector('#modal-benefit-constraints').textContent=benefit.constraints;
  document.querySelector('#modal-question').textContent=TRANSFER_QUESTIONS[c.pathway]||'What site-specific evidence is still required before this precedent can support design, approval or investment decisions elsewhere?';
  document.querySelector('#modal-reviewed').textContent=c.lastReviewed;
  document.querySelector('#modal-sources').innerHTML=c.sources.map(source=>`<a href="${escapeHTML(source.url)}" target="_blank" rel="noopener">${escapeHTML(source.label)} ↗</a>`).join('');
  document.querySelector('#modal-citation').textContent=`Waste2Resource (${new Date().getFullYear()}). ${c.title}. Technical Library. ${recordURL(c.id)} (reviewed ${c.lastReviewed}).`;
  document.querySelector('#report-record').href=`mailto:hello@waste2resource.com.au?subject=${encodeURIComponent(`Correction or evidence for: ${c.title}`)}&body=${encodeURIComponent(`Record: ${recordURL(c.id)}\n\nSuggested correction or additional evidence:\n`)}`;
  const url=new URL(window.location.href);url.searchParams.set('case',c.id);history.replaceState({caseId:c.id},'',url);
  modal.showModal();
}

function visibleCases(){
  const q=search.value.trim().toLowerCase();
  return CASES.filter(c=>(!region.value||c.region===region.value)&&(!material.value||c.material===material.value)&&(!pathway.value||c.pathway===pathway.value)&&(!q||`${c.title} ${c.location} ${c.commodity} ${c.waste} ${c.pathway} ${c.stage} ${c.evidence} ${c.summary} ${c.sourceState}`.toLowerCase().includes(q)));
}

function renderPathwayLegend(){
  const legend=document.querySelector('#pathway-legend'); if(!legend)return;
  legend.innerHTML=Object.entries(PATHWAY_META).map(([label,meta])=>{const total=CASES.filter(c=>c.pathway===label).length;return `<button type="button" class="legend-item pathway-${meta.slug}" data-pathway="${escapeHTML(label)}" aria-pressed="${pathway.value===label}"><i></i><span>${escapeHTML(label)}</span><b>${total}</b></button>`}).join('');
  legend.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{pathway.value=pathway.value===button.dataset.pathway?'':button.dataset.pathway;visibleLimit=CASE_BATCH_SIZE;renderCards()}));
}

function renderRegionShortcuts(){
  const shortcuts=document.querySelector('#region-shortcuts'); if(!shortcuts)return;
  const options=[['',`All regions`,CASES.length],...REGION_ORDER.map(label=>[label,label,CASES.filter(c=>c.region===label).length])];
  shortcuts.innerHTML=options.map(([value,label,total])=>`<button type="button" data-region="${escapeHTML(value)}" aria-pressed="${region.value===value}">${escapeHTML(label)} <b>${total}</b></button>`).join('');
  shortcuts.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{region.value=button.dataset.region;visibleLimit=CASE_BATCH_SIZE;renderCards()}));
}

function renderCards(){
  const visible=visibleCases();
  const displayed=visible.slice(0,visibleLimit);
  cards.innerHTML=displayed.map(c=>{const meta=pathwayMeta(c.pathway),sourceLabel=`${c.sources.length} source${c.sources.length===1?'':'s'}`,maturity=maturityFor(c),fact=(label,value)=>`<div role="group" aria-label="${escapeHTML(label)}: ${escapeHTML(value)}."><dt aria-hidden="true">${escapeHTML(label)}:</dt><dd aria-hidden="true">${escapeHTML(value)}.</dd></div>`;return `<article class="case-card pathway-${meta.slug}"><div class="case-card-top"><span class="case-icon" aria-hidden="true">${meta.code}</span></div><span class="meta">${escapeHTML(c.location)}</span><h2><a href="/technical-library/cases/${encodeURIComponent(c.id)}/">${escapeHTML(c.title)}</a></h2><dl class="case-data">${fact('Residue',c.waste)}${fact('Commodity',c.commodity)}${fact('Evidence',c.evidence)}${fact('Project stage',c.stage)}${fact('Maturity',maturity)}</dl><p class="case-summary">${escapeHTML(c.summary)}</p><div class="case-source-state"><b>Source states:</b><p>${escapeHTML(c.sourceState)}</p><a href="${escapeHTML(c.sources[0].url)}" target="_blank" rel="noopener">Verify in source ↗</a></div><div class="case-card-foot"><span class="pathway-label"><i></i>${escapeHTML(c.pathway)}</span><span>${sourceLabel}</span></div><button type="button" data-id="${escapeHTML(c.id)}">Quick view →</button><small class="review-date">Published · Reviewed ${escapeHTML(c.lastReviewed)}</small></article>`}).join('');
  count.textContent=visible.length?`Showing ${displayed.length} of ${visible.length} case stud${visible.length===1?'y':'ies'}`:'No case studies match these filters';
  if(showMoreButton){const remaining=visible.length-displayed.length;showMoreButton.hidden=remaining<=0;showMoreButton.textContent=`Show ${Math.min(CASE_BATCH_SIZE,remaining)} more`;}
  if(paginationStatus)paginationStatus.textContent=visible.length>displayed.length?`${visible.length-displayed.length} more cases are available in this filtered view.`:`All ${visible.length} matching case${visible.length===1?' is':'s are'} shown.`;
  cards.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>showCase(button.dataset.id)));
  renderPathwayLegend(); renderRegionShortcuts(); renderMapMarkers(visible);
}

function projectPoint(lng,lat){return mapProjection?mapProjection([lng,lat]):[((lng+180)/360)*1200,((90-lat)/180)*600]}
function spreadPoint(base,placed){const collisions=placed.filter(point=>Math.hypot(point[0]-base[0],point[1]-base[1])<18).length;if(!collisions)return base;const angle=collisions*2.35,radius=10+Math.ceil(collisions/5)*5;return [base[0]+Math.cos(angle)*radius,base[1]+Math.sin(angle)*radius]}

function setMapPreview(id){
  const c=CASES.find(item=>item.id===id); if(!c||!mapPreview)return;
  selectedCaseId=id; const meta=pathwayMeta(c.pathway);
  mapPreview.innerHTML=`<p class="eyebrow light">Selected map record</p><span class="preview-location">${escapeHTML(c.location)} · ${escapeHTML(c.region)}</span><h2>${escapeHTML(c.title)}</h2><div class="preview-tags"><span class="pathway-${meta.slug}"><i></i>${escapeHTML(c.pathway)}</span><span>${escapeHTML(c.readiness)}</span></div><p>${escapeHTML(c.summary)}</p><dl><div><dt>Material</dt><dd>${escapeHTML(c.waste)}</dd></div><div><dt>Evidence</dt><dd>${escapeHTML(c.evidence)}</dd></div></dl><button type="button" data-preview-id="${escapeHTML(c.id)}">Open full technical record →</button>`;
  mapPreview.querySelector('button').addEventListener('click',()=>showCase(c.id));
  document.querySelectorAll('.geo-marker').forEach(marker=>marker.classList.toggle('selected',marker.dataset.caseId===id));
}

function showMapTooltip(c,event){
  if(!mapTooltip)return; const map=document.querySelector('.map'),rect=map.getBoundingClientRect(),meta=pathwayMeta(c.pathway),width=230;
  mapTooltip.innerHTML=`<b>${escapeHTML(c.title)}</b><span>${escapeHTML(c.location)}</span><small class="pathway-${meta.slug}">${escapeHTML(c.pathway)} · ${escapeHTML(c.readiness)}</small>`;
  mapTooltip.hidden=false; const x=Math.min(Math.max(event.clientX-rect.left+14,8),Math.max(8,rect.width-width-8)),y=Math.min(Math.max(event.clientY-rect.top+14,8),Math.max(8,rect.height-92));mapTooltip.style.left=`${x}px`;mapTooltip.style.top=`${y}px`;
}
function hideMapTooltip(){if(mapTooltip)mapTooltip.hidden=true}

function renderMapMarkers(visible=CASES){
  const layer=document.querySelector('#marker-layer'),status=document.querySelector('#map-status');if(!layer){if(status)status.hidden=false;return}
  layer.replaceChildren(); const placed=[];
  visible.forEach(c=>{const meta=pathwayMeta(c.pathway),point=spreadPoint(projectPoint(c.lng,c.lat),placed);placed.push(point);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('class',`geo-marker pathway-${meta.slug}`);dot.setAttribute('cx',point[0]);dot.setAttribute('cy',point[1]);dot.setAttribute('r','7');dot.setAttribute('tabindex','0');dot.setAttribute('role','button');dot.setAttribute('aria-label',`${c.location}: ${c.title}`);dot.dataset.caseId=c.id;dot.addEventListener('pointerenter',event=>showMapTooltip(c,event));dot.addEventListener('pointermove',event=>showMapTooltip(c,event));dot.addEventListener('pointerleave',hideMapTooltip);dot.addEventListener('focus',()=>setMapPreview(c.id));dot.addEventListener('click',()=>setMapPreview(c.id));dot.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setMapPreview(c.id)}});const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=`${c.location}: ${c.title}`;dot.appendChild(title);layer.appendChild(dot)});
  if(!visible.length){selectedCaseId=null;if(mapPreview)mapPreview.innerHTML='<p class="eyebrow light">Selected map record</p><p class="map-preview-empty">No cases match the current filters.</p>'}else if(!visible.some(c=>c.id===selectedCaseId)){setMapPreview(visible[0].id)}else{setMapPreview(selectedCaseId)}
  if(status)status.hidden=true;
}

if(cards&&count&&search&&region&&material&&pathway){[search,region,material,pathway].forEach(control=>control.addEventListener('input',()=>{visibleLimit=CASE_BATCH_SIZE;renderCards()}));if(showMoreButton)showMoreButton.addEventListener('click',()=>{visibleLimit+=CASE_BATCH_SIZE;renderCards();const firstNewCard=cards.children[Math.max(0,visibleLimit-CASE_BATCH_SIZE)];if(firstNewCard)firstNewCard.scrollIntoView({block:'nearest'})});renderCards()}
const modalClose=document.querySelector('#modal-close');if(modalClose&&modal){modalClose.addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()})}
const copyRecordLink=document.querySelector('#copy-record-link');
if(copyRecordLink){copyRecordLink.addEventListener('click',async()=>{const caseId=new URL(window.location.href).searchParams.get('case'),status=document.querySelector('#copy-status');if(!caseId)return;try{await navigator.clipboard.writeText(recordURL(caseId));status.textContent='Link copied.'}catch(error){status.textContent='Copy is unavailable. Use the address in your browser.'}})}
window.addEventListener('load',async()=>{const status=document.querySelector('#map-status'),land=document.querySelector('#land-layer');if(!land)return;if(!window.d3||!window.topojson){if(status){status.hidden=false;status.textContent='Live map data is unavailable. The built-in map and case filters remain available.'}return}try{const response=await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json');if(!response.ok)throw new Error('World data request failed');const topology=await response.json(),world=topojson.feature(topology,topology.objects.countries);mapProjection=d3.geoNaturalEarth1().fitExtent([[18,18],[1182,582]],world);const path=d3.geoPath(mapProjection);d3.select(land).selectAll('*').remove();d3.select(land).selectAll('path').data(world.features).join('path').attr('d',path);renderMapMarkers(visibleCases());if(status)status.hidden=true}catch(error){mapProjection=null;renderMapMarkers(visibleCases());if(status){status.hidden=false;status.textContent='Map detail is unavailable. Browse all cases using the markers, list and filters.'}}});
const requestedCase=new URL(window.location.href).searchParams.get('case');if(requestedCase&&CASES.some(item=>item.id===requestedCase)){setTimeout(()=>showCase(requestedCase),0)}
