const CASES=[
{id:'plombieres',title:'Tailings for facing bricks',location:'Plombières, Belgium',region:'Europe',material:'Tailings',waste:'Sulphidic tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:50.736,lng:5.961,summary:'Untreated tailings were assessed in facing-brick blends with environmental and lifecycle evaluation.',detail:'A peer-reviewed study assessed untreated Plombières tailings in facing-brick blends, reporting satisfactory technical properties and regulatory compliance across the assessed scenarios.',source:'https://www.sciencedirect.com/science/article/pii/S095965262202707X'},
{id:'nador',title:'Iron tailings in fired bricks',location:'Nador, Morocco',region:'Africa',material:'Tailings',waste:'Iron-ore tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:35.168,lng:-2.934,summary:'Inactive-mine iron tailings were evaluated as an additive in fired red-clay bricks.',detail:'Researchers evaluated tailings from an inactive iron mine as an additive in fired red-clay bricks, reporting material proportions and performance.',source:'https://orbi.uliege.be/handle/2268/335849'},
{id:'pamaka',title:'Cement-tailings bricks',location:'Pamaka, Suriname',region:'South America',material:'Tailings',waste:'Artisanal gold tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:4.4,lng:-54.4,summary:'Artisanal gold-mining waste was tested in cement-tailings bricks for non-loadbearing masonry.',detail:'The study tested cement-tailings bricks made from artisanal gold-mining waste and reported that the units met the cited criteria for non-loadbearing masonry.',source:'https://www.sciencedirect.com/science/article/pii/S2772912525000673'},
{id:'ecuador',title:'Tailings in concrete blocks',location:'Southern Ecuador',region:'South America',material:'Tailings',waste:'Gold-mining tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:-3.994,lng:-79.204,summary:'Gold tailings were assessed as a partial substitute for sand in concrete-block production.',detail:'Researchers evaluated gold-mining tailings as a partial sand substitute in concrete blocks, including physical, chemical, mineralogical and leaching assessment.',source:'https://www.mdpi.com/2071-1050/14/23/16285'},
{id:'donimalai',title:'Donimalai tailings bricks',location:'Karnataka, India',region:'Asia-Pacific',material:'Tailings',waste:'Iron-ore tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:15.094,lng:76.549,summary:'Iron-ore tailings from Donimalai Mines were tested in brick formulations.',detail:'A study tested brick compositions incorporating Donimalai iron-ore tailings alongside cement, sand and sodium silicate.',source:'https://nopr.niscpr.res.in/handle/123456789/56477'},
{id:'wa',title:'Geopolymer tailings bricks',location:'Western Australia',region:'Asia-Pacific',material:'Tailings',waste:'Iron-ore tailings',pathway:'Construction',evidence:'Peer-reviewed research',lat:-25,lng:118,summary:'Western Australian iron-ore tailings were studied as feedstock for geopolymer bricks.',detail:'Research investigated Western Australian iron-ore tailings as the main feedstock for geopolymer bricks, including strength and durability testing.',source:'https://ro.ecu.edu.au/ecuworkspost2013/473/'},
{id:'ergo',title:'Ergo gold retreatment',location:'Gauteng, South Africa',region:'Africa',material:'Tailings',waste:'Gold tailings',pathway:'Metals recovery',evidence:'Operating project / company source',lat:-26.255,lng:28.146,summary:'Historic tailings are reclaimed and processed through a surface gold-retreatment operation.',detail:'DRDGOLD operates a surface gold-tailings retreatment business. Reclaimed material is re-pulped and treated through screens, cyclones, mills and carbon-in-leach technology.',source:'https://www.drdgold.com/our-business/ergo'},
{id:'missouri',title:'Missouri cobalt recovery',location:'Missouri, USA',region:'North America',material:'Tailings',waste:'Cobalt and nickel tailings',pathway:'Metals recovery',evidence:'Institutional case study',lat:37.5,lng:-92.3,summary:'Legacy tailings are reprocessed for cobalt and other concentrates alongside closure work.',detail:'An ITRC case study documents tailings reprocessing aimed at cobalt and nickel concentrates, paired with capping and closure of remaining material.',source:'https://mw-1.itrcweb.org/project-summaries-and-case-studies/'},
{id:'wheal',title:'Wheal Jane water treatment',location:'Cornwall, United Kingdom',region:'Europe',material:'Mine water',waste:'Contaminated mine water',pathway:'Water treatment',evidence:'Government case study',lat:50.241,lng:-5.054,summary:'A long-running treatment scheme manages contaminated drainage from the former tin mine.',detail:'The UK Environment Agency documents the Wheal Jane mine-water treatment scheme and management of contaminated drainage from the former tin mine.',source:'https://www.gov.uk/government/case-studies/wheal-jane-mine-water-treatment-scheme'},
{id:'kittimac',title:'Kittimac tailings remediation',location:'Colorado, USA',region:'North America',material:'Tailings',waste:'Tailings and treatment sludge',pathway:'Land restoration',evidence:'Institutional case study',lat:39.05,lng:-107.9,summary:'Treatment sludge was blended with contaminated tailings before capping and revegetation.',detail:'High-pH treatment sludge was mixed with lead-contaminated tailings to reduce metal mobility. Treated material was intended for capping and revegetation.',source:'https://mw-1.itrcweb.org/project-summaries-and-case-studies/'},
{id:'mountkeith',title:'Mount Keith carbon sink',location:'Western Australia',region:'Asia-Pacific',material:'Tailings',waste:'Ultramafic nickel tailings',pathway:'Carbon mineralisation',evidence:'Peer-reviewed research',lat:-27.26,lng:120.55,summary:'Research documents atmospheric CO₂ becoming stable carbonate minerals in nickel tailings.',detail:'Published research at Mount Keith documents atmospheric carbon dioxide being trapped in tailings through carbonation reactions that form hydromagnesite.',source:'https://acsess.onlinelibrary.wiley.com/doi/10.2136/vzj2011.0053'}
];
const cards=document.querySelector('#cards'),count=document.querySelector('#result-count'),search=document.querySelector('#search'),region=document.querySelector('#region'),material=document.querySelector('#material'),pathway=document.querySelector('#pathway');
const modal=document.querySelector('#detail-modal');
function showCase(id){const c=CASES.find(x=>x.id===id);if(!c)return;document.querySelector('#modal-title').textContent=c.title;document.querySelector('#modal-location').textContent=c.location;document.querySelector('#modal-text').textContent=c.detail;document.querySelector('#modal-material').textContent=c.waste;document.querySelector('#modal-pathway').textContent=c.pathway;document.querySelector('#modal-evidence').textContent=c.evidence;document.querySelector('#modal-source').href=c.source;modal.showModal();}
function renderCards(){const q=search.value.trim().toLowerCase();const visible=CASES.filter(c=>(!region.value||c.region===region.value)&&(!material.value||c.material===material.value)&&(!pathway.value||c.pathway===pathway.value)&&(!q||`${c.title} ${c.location} ${c.waste} ${c.pathway} ${c.summary}`.toLowerCase().includes(q)));cards.innerHTML=visible.map(c=>`<article class="case-card"><span class="meta">${c.location} · ${c.waste}</span><h2>${c.title}</h2><p>${c.summary}</p><button type="button" data-id="${c.id}">${c.pathway} · View record →</button></article>`).join('');count.textContent=`${visible.length} case stud${visible.length===1?'y':'ies'} in view`;cards.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>showCase(b.dataset.id)));}
[search,region,material,pathway].forEach(el=>el.addEventListener('input',renderCards));renderCards();document.querySelector('#modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
function fallbackMarkers(){const layer=document.querySelector('#marker-layer');CASES.forEach(c=>{const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('class','geo-marker');dot.setAttribute('cx',((c.lng+180)/360)*1200);dot.setAttribute('cy',((90-c.lat)/180)*600);dot.setAttribute('r','7');dot.setAttribute('tabindex','0');dot.setAttribute('role','button');dot.setAttribute('aria-label',`${c.location}: ${c.title}`);dot.addEventListener('click',()=>showCase(c.id));dot.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showCase(c.id)}});const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=`${c.location} — ${c.title}`;dot.appendChild(title);layer.appendChild(dot);});}fallbackMarkers();
window.addEventListener('load',()=>{if(!window.d3)return;fetch('https://cdn.jsdelivr.net/gh/holtzy/D3-graph-gallery@master/DATA/world.geojson').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(world=>{const svg=d3.select('#case-map');svg.selectAll('*').remove();const projection=d3.geoEquirectangular().fitSize([1200,600],world),geoPath=d3.geoPath(projection);svg.append('path').datum(d3.geoGraticule10()).attr('class','geo-grid').attr('d',geoPath);svg.append('g').selectAll('path').data(world.features).join('path').attr('class','geo-land').attr('d',geoPath);const layer=svg.append('g');CASES.forEach(c=>{const [x,y]=projection([c.lng,c.lat]);const dot=layer.append('circle').attr('class','geo-marker').attr('cx',x).attr('cy',y).attr('r',7).attr('tabindex',0).attr('role','button').attr('aria-label',`${c.location}: ${c.title}`);dot.append('title').text(`${c.location} — ${c.title}`);dot.on('click',()=>showCase(c.id)).on('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showCase(c.id)}});});}).catch(()=>{});});
